# Generated by Django 2.0.6 on 2018-06-17 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200, null=True)),
                ('population', models.IntegerField(verbose_name='Population')),
                ('languages', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed', models.CharField(max_length=200, null=True)),
                ('c_pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Countries.countries')),
            ],
        ),
    ]
